spring:
  application:
    name: calendar
  cloud:
    stream:
      kafka:
        binder:
          brokers: education-kafka:9092  # ${vcap.services.kakfa.host_port} and inject value from env variable
          zkNodes: education-kafka-zookeeper:2181
      bindings:
        class-topic:
          destination: class.topic
          contentType: application/json


eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    statusPageUrlPath: ${server.servletPath}info
    healthCheckUrlPath: ${server.servletPath}health
    metadataMap:
      deployment: local
      profile: local
