spring:
  application:
    name: zuul-router


server:
  port: 8080
  servletPath: /

zuul:
  debug:
    request: true
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  addProxyHeaders: true

  routes:
    courses:
      path: /courses/**
      serviceId: courses
      #url: http://10.0.2.15:8087
      stripPrefix: false
    clazzes:
      path: /clazzes/**
      serviceId: courses
      #url: http://10.0.2.15:8087
      stripPrefix: false
    calendar:
      path: /schedules/**
      serviceId: calendar
      #url: http://10.0.2.15:8088
      stripPrefix: false
    marketing:
      path: /marketing/**
      #serviceId: marketing
      url: http://10.0.2.15:8089
      stripPrefix: false

endpoints:
  routes:
    sensitive: false

ribbon:
  # NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
  # listOfServers: http://example1.com,http://example2.com
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
  ServerListRefreshInterval: 2000
  ConnectTimeout: 60000
  ReadTimeout: 60000

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
#      defaultZone: ${eureka_url}
    healthcheck:
      enabled: true
  instance:
#    hostname: ${spring.application.name}
    preferIpAddress: false
    instanceId:  ${spring.application.name}:${random.value}
    statusPageUrlPath: ${server.servletPath}info
    healthCheckUrlPath: ${server.servletPath}health



hystrix:
  threadpool:
    default:
      coreSize: 1000
      maximumSize: 10000
      queueSizeRejectionThreshold: -1
      maxQueueSize: -1
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 61000