server:
  port: 8761

eureka:
  instance:
    hostname: eureka-server
    preferIpAddress: true
    instanceId: ${random.int}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false

spring:
  cloud:
    inetutils:
      preferredNetworks:
        - 10.0
