spring:
  application:
    name: courses
  cloud:
    stream:
      kafka:
        binder:
          brokers: education-kafka:9092  # ${vcap.services.kakfa.host_port} and inject value from env variable
          zkNodes: education-kafka-zookeeper:2181
      bindings:
        class-topic:
          destination: class.topic
          contentType: application/json
#    inetutils:
#      ignored-interfaces:
#        - eth0
#        - eth1
#        - eth2
#        - eth3
#        - lo

server:
  port: 8087
  servletPath: /

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: ${HOSTNAME}
    preferIpAddress: false
    instanceId:  ${spring.application.name}:${random.value}
    statusPageUrlPath: ${server.servletPath}info
    healthCheckUrlPath: ${server.servletPath}health
    metadataMap:
      deployment: local
      profile: local
